services:
  php:
    extra_hosts:
        - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}

    container_name: laravel_php

    working_dir: /var/www

    volumes:
      - ./src:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

    networks:
      - laravel

  nginx:
    image: nginx:alpine

    container_name: laravel_nginx

    ports:
      - "8080:80"

    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php

    networks:
      - laravel

  postgres:
    image: postgres:17

    container_name: laravel_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - laravel

  redis:
    image: redis:alpine

    container_name: laravel_redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - laravel

  node:
    image: node:22-alpine
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
